<a href="https://colab.research.google.com/github/DanielHughes1580/deep-learning-challenge/blob/main/Starter_Code_Optimised.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [6]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(["EIN"], 1)

<ipython-input-7-748f058108c5>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df = application_df.drop(["EIN"], 1)

In [8]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [9]:
# Eduardo's Add-In

# Look at NAME value counts for binning
name_counts = application_df['NAME'].value_counts()
#  How many name counts are greater than 5?
name_counts[name_counts>5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [10]:
# Determine which values to replace if counts are less than or equal to 5.
names_to_replace = list(name_counts[name_counts <= 5].index)

# Replace in dataframe
for app in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(app,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [11]:
# Look at APPLICATION_TYPE value counts for binning
app_value = application_df["APPLICATION_TYPE"].value_counts()
app_value

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [12]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_value[app_value<=25].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
T13         66
Other       27
T12         27
Name: APPLICATION_TYPE, dtype: int64

In [13]:
# Look at CLASSIFICATION value counts for binning
app_class = application_df["CLASSIFICATION"].value_counts()
app_class

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [14]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE

In [15]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`


# Eduardo's Add-In app_class<=1000
classifications_to_replace = list(app_class[app_class<=1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [16]:
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,Other,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,Other,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,Other,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,Other,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [17]:
# Eduardo's Add-In

# Generate our categorical variable lists
application_cat = application_df.dtypes[application_df.dtypes == "object"].index.tolist()
application_cat

['NAME',
 'APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [18]:
# Convert categorical data to numeric with `pd.get_dummies`
dummy = pd.get_dummies(application_df)
dummy.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [19]:
# Split our preprocessed data into our features and target arrays
y = dummy["IS_SUCCESSFUL"].values
X = dummy.drop(columns = "IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [20]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [21]:
len(X_train_scaled)

25724

## Compile, Train and Evaluate the Model

In [22]:
# Eduardo's Add-In

# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input = len(X_train_scaled[0])
first_layer = 100
second_layer = 50
third_layer = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = first_layer, input_dim = number_input, activation = "relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = second_layer, activation = "sigmoid"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units = third_layer, activation = "sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               40200

 dense_1 (Dense)             (None, 50)                5050

 dense_2 (Dense)             (None, 10)                510

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 45771 (178.79 KB)
Trainable params: 45771 (178.79 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [23]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 3ms/step - loss: 0.5115 - accuracy: 0.7652
Epoch 2/50
804/804 [==============================] - 3s 3ms/step - loss: 0.4511 - accuracy: 0.7957
Epoch 3/50
804/804 [==============================] - 3s 3ms/step - loss: 0.4386 - accuracy: 0.7969
Epoch 4/50
804/804 [==============================] - 3s 3ms/step - loss: 0.4327 - accuracy: 0.7977
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4288 - accuracy: 0.7981
Epoch 6/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4264 - accuracy: 0.7986
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4240 - accuracy: 0.7996
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4223 - accuracy: 0.8002
Epoch 9/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4207 - accuracy: 0.8005
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4195 - accuracy: 0.7997
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4182 - accuracy: 0.8005
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4168 - accuracy: 0.8015
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4161 - accuracy: 0.8009
Epoch 14/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4150 - accuracy: 0.8032
Epoch 15/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4141 - accuracy: 0.8022
Epoch 16/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4135 - accuracy: 0.8030
Epoch 17/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4131 - accuracy: 0.8035
Epoch 18/50
804/804 [==============================] - 3s 3ms/step - loss: 0.4119 - accuracy: 0.8035
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4119 - accuracy: 0.8033
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4107 - accuracy: 0.8036
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4103 - accuracy: 0.8035
Epoch 22/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4097 - accuracy: 0.8044
Epoch 23/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4095 - accuracy: 0.8034
Epoch 24/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4083 - accuracy: 0.8044
Epoch 25/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4086 - accuracy: 0.8044
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4079 - accuracy: 0.8046
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4077 - accuracy: 0.8047
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4069 - accuracy: 0.8051
Epoch 29/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4067 - accuracy: 0.8048
Epoch 30/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4064 - accuracy: 0.8043
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4065 - accuracy: 0.8046
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4056 - accuracy: 0.8051
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4055 - accuracy: 0.8052
Epoch 34/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4052 - accuracy: 0.8059
Epoch 35/50
804/804 [==============================] - 3s 3ms/step - loss: 0.4046 - accuracy: 0.8061
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4049 - accuracy: 0.8070
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4045 - accuracy: 0.8051
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4040 - accuracy: 0.8064
Epoch 39/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4035 - accuracy: 0.8065
Epoch 40/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8066
Epoch 41/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8075
Epoch 42/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4029 - accuracy: 0.8059
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4025 - accuracy: 0.8069
Epoch 44/50
804/804 [==============================] - 3s 3ms/step - loss: 0.4027 - accuracy: 0.8076
Epoch 45/50
804/804 [==============================] - 3s 3ms/step - loss: 0.4021 - accuracy: 0.8069
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4019 - accuracy: 0.8071
Epoch 47/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4017 - accuracy: 0.8085
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.4015 - accuracy: 0.8070
Epoch 49/50
804/804 [==============================] - 3s 3ms/step - loss: 0.4016 - accuracy: 0.8071
Epoch 50/50
804/804 [==============================] - 3s 4ms/step - loss: 0.4014 - accuracy: 0.8080

In [25]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4598 - accuracy: 0.7883 - 555ms/epoch - 2ms/step
Loss: 0.45980367064476013, Accuracy: 0.7883381843566895

In [26]:
# Export our model to HDF5 file
filename = "AlphabetSoupCharity_Optimized.h5"
nn.save(filename)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(